def build_markdown(sector, ai_response):

    try:
        text = ai_response["candidates"][0]["content"]["parts"][0]["text"]
    except:
        text = "Error generating report"

    return f"""
# Market Analysis: {sector}

{text}

---
Generated by API
"""